# Generated by Django 4.1.5 on 2023-03-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='about',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='user_name',
        ),
        migrations.AddField(
            model_name='newuser',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
