# Generated by Django 4.1.5 on 2023-03-18 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_category'),
        ('user', '0002_rename_first_name_newuser_name_remove_newuser_about_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('delivery_address', models.TextField(max_length=150)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ordered_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'ordering': ('-order_date',),
            },
        ),
    ]
