# Generated by Django 4.1.5 on 2023-03-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_orders_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='state',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='delivery_address',
        ),
        migrations.AddField(
            model_name='orders',
            name='address_line_1',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orders',
            name='address_line_2',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='orders',
            name='city',
            field=models.TextField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='orders',
            name='country',
            field=models.TextField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='orders',
            name='pincode',
            field=models.TextField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='orders',
            name='state',
            field=models.TextField(blank=True, max_length=25),
        ),
    ]
