# Generated by Django 4.1.5 on 2023-03-28 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_newuser_address_line_1_newuser_address_line_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.TextField(blank=True, max_length=100)),
                ('address_line_2', models.TextField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=25)),
                ('state', models.CharField(blank=True, max_length=25)),
                ('pincode', models.CharField(blank=True, max_length=25)),
                ('country', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='state',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='city',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='country',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='state',
        ),
        migrations.AddField(
            model_name='newuser',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.address'),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.address'),
        ),
    ]
