# Generated by Django 4.1.5 on 2023-03-28 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_address_remove_newuser_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.address'),
        ),
    ]
