# Generated by Django 4.1.5 on 2023-03-28 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_newuser_address_orders_delivery_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='delivery_address',
        ),
    ]
